import type { QRStyleConfig } from "./types";

export interface QRTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  style: QRStyleConfig;
}

export const templates: QRTemplate[] = [
  {
    id: "restaurant",
    name: "Restaurant",
    category: "Food & Drink",
    description: "Warm orange and brown tones with rounded dots, perfect for menus and dining.",
    style: {
      dotStyle: "rounded",
      cornerSquareStyle: "square",
      cornerDotStyle: "square",
      fgColor: "#A0522D",
      bgColor: "#FFF8F0",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "event",
    name: "Event",
    category: "Events",
    description: "Bold black and red with classy dots for tickets, invitations, and posters.",
    style: {
      dotStyle: "classy",
      cornerSquareStyle: "dot",
      cornerDotStyle: "dot",
      fgColor: "#1A1A1A",
      bgColor: "#FFFFFF",
      gradient: {
        type: "linear",
        rotation: 45,
        colorStops: [
          { offset: 0, color: "#1A1A1A" },
          { offset: 1, color: "#CC0000" },
        ],
      },
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "business",
    name: "Business",
    category: "Professional",
    description: "Clean navy blue on white with square styling for corporate and professional use.",
    style: {
      dotStyle: "square",
      cornerSquareStyle: "square",
      cornerDotStyle: "square",
      fgColor: "#1B2A4A",
      bgColor: "#FFFFFF",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "social",
    name: "Social",
    category: "Social Media",
    description: "Vibrant purple-to-pink gradient with dot styling for social media profiles.",
    style: {
      dotStyle: "dots",
      cornerSquareStyle: "dot",
      cornerDotStyle: "dot",
      fgColor: "#8B5CF6",
      bgColor: "#FFFFFF",
      gradient: {
        type: "linear",
        rotation: 135,
        colorStops: [
          { offset: 0, color: "#8B5CF6" },
          { offset: 1, color: "#EC4899" },
        ],
      },
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    category: "Simple",
    description: "Pure black and white with square dots. No frills, maximum scanability.",
    style: {
      dotStyle: "square",
      cornerSquareStyle: "square",
      cornerDotStyle: "square",
      fgColor: "#000000",
      bgColor: "#FFFFFF",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "bold",
    name: "Bold",
    category: "Statement",
    description: "Dark green with extra-rounded dots for a heavy, eye-catching look.",
    style: {
      dotStyle: "extra-rounded",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      fgColor: "#1B5E20",
      bgColor: "#FFFFFF",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "neon",
    name: "Neon",
    category: "Dark",
    description: "Neon green on near-black background with dot styling for a dark aesthetic.",
    style: {
      dotStyle: "dots",
      cornerSquareStyle: "dot",
      cornerDotStyle: "dot",
      fgColor: "#00FF88",
      bgColor: "#0A0A0B",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    category: "Luxury",
    description: "Dark gray to gold gradient with classy-rounded dots for a premium feel.",
    style: {
      dotStyle: "classy-rounded",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      fgColor: "#333333",
      bgColor: "#FFFDF5",
      gradient: {
        type: "linear",
        rotation: 180,
        colorStops: [
          { offset: 0, color: "#333333" },
          { offset: 1, color: "#C8A84E" },
        ],
      },
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "tech",
    name: "Tech",
    category: "Technology",
    description: "Purple on dark navy background with rounded dots for a modern tech vibe.",
    style: {
      dotStyle: "rounded",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      fgColor: "#7C5CFF",
      bgColor: "#1A1A2E",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
  {
    id: "nature",
    name: "Nature",
    category: "Organic",
    description: "Forest green on cream with rounded dots for an organic, natural appearance.",
    style: {
      dotStyle: "rounded",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      fgColor: "#2D6A4F",
      bgColor: "#FEFAE0",
      gradient: null,
      logoUrl: null,
      logoSize: 0.25,
      errorCorrection: "M",
      frame: null,
    },
  },
];
